on:
  workflow_dispatch:

jobs:
  actions_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: using local actions
        # Using a local action
        uses: ./.github/actions/local-action
        # we can pass parameters to the local action
        with:
          name: 'local action'
          message: 'this is a local action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hybrid_job:
    runs-on: ubuntu-latest
    steps:
      # this runs on the vm
      - name: Run a command on ubuntu vm
        run: echo "Hello from the VM!"

      # this runs on alpine container
      - name: Run a command in a Docker container
        uses: docker://alpine:latest
        # passing params for the container
        with:
          entrypoint: /bin/sh
          # runs on the shell within the alpine container which are running on ubuntu vm
          args: |
            -c "echo 'Hello from the Alpine container!'"

      - name: Run a command on ubuntu vm
        run: echo "Hello Again from the VM!"

  dockerized_job:
    runs-on: ubuntu-latest
    # github container registery
    container:
      image: ghcr.io/your-org/your-repo:20
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # all the steps will run on the node container
    steps:
      - run: node --version
      - run: echo "this whole job run on docker container"
