name: commands

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: check for deprecated code

        # simulate we found a deprecated code
        # using warning annotation
        run: |
          deprecated=true
          if [[ deprecated ]]; then

            echo "::warning::Deprecated code found"
          fi

      - name: check for file exist
        run: |
          if  [-f "config.yml"]; then
            echo "::error::file config.yml does not exist"
          fi

      - name: setting up env
        run: echo "API_KEY=123" >> $GITHUB_ENV

      - name: using api key
        run: echo "using the api key $API_KEY"
