on:
  workflow_dispatch:

jobs:
  matrix_job:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: setup node js env
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}

    # this job will run for each runner 3 times with each node version
    # so total 9 times
